
const countries = [
    { "name": "Afghanistan", "value": "AF", "id": 1 },
    { "name": "Aland Islands", "value": "AX", "id": 2 },
    { "name": "Albania", "value": "AL", "id": 3 },
    { "name": "Algeria", "value": "DZ", "id": 4 },
    { "name": "American Samoa", "value": "AS", "id": 5 },
    { "name": "Andorra", "value": "AD", "id": 6 },
    { "name": "Angola", "value": "AO", "id": 7 },
    { "name": "Anguilla", "value": "AI", "id": 8 },
    { "name": "Antarctica", "value": "AQ", "id": 9 },
    { "name": "Antigua and Barbuda", "value": "AG", "id": 10 },
    { "name": "Argentina", "value": "AR", "id": 11 },
    { "name": "Armenia", "value": "AM", "id": 12 },
    { "name": "Aruba", "value": "AW", "id": 13 },
    { "name": "Australia", "value": "AU", "id": 14 },
    { "name": "Austria", "value": "AT", "id": 15 },
    { "name": "Azerbaijan", "value": "AZ", "id": 16 },
    { "name": "Bahamas", "value": "BS", "id": 17 },
    { "name": "Bahrain", "value": "BH", "id": 18 },
    { "name": "Bangladesh", "value": "BD", "id": 19 },
    { "name": "Barbados", "value": "BB", "id": 20 },
    { "name": "Belarus", "value": "BY", "id": 21 },
    { "name": "Belgium", "value": "BE", "id": 22 },
    { "name": "Belize", "value": "BZ", "id": 23 },
    { "name": "Benin", "value": "BJ", "id": 24 },
    { "name": "Bermuda", "value": "BM", "id": 25 },
    { "name": "Bhutan", "value": "BT", "id": 26 },
    { "name": "Bolivia", "value": "BO", "id": 27 },
    { "name": "Bonaire, Sint Eustatius and Saba", "value": "BQ", "id": 28 },
    { "name": "Bosnia and Herzegovina", "value": "BA", "id": 29 },
    { "name": "Botswana", "value": "BW", "id": 30 },
    { "name": "Bouvet Island", "value": "BV", "id": 31 },
    { "name": "Brazil", "value": "BR", "id": 32 },
    { "name": "British Indian Ocean Territory", "value": "IO", "id": 33 },
    { "name": "Brunei Darussalam", "value": "BN", "id": 34 },
    { "name": "Bulgaria", "value": "BG", "id": 35 },
    { "name": "Burkina Faso", "value": "BF", "id": 36 },
    { "name": "Burundi", "value": "BI", "id": 37 },
    { "name": "Cambodia", "value": "KH", "id": 38 },
    { "name": "Cameroon", "value": "CM", "id": 39 },
    { "name": "Canada", "value": "CA", "id": 40 },
    { "name": "Cape Verde", "value": "CV", "id": 41 },
    { "name": "Cayman Islands", "value": "KY", "id": 42 },
    { "name": "Central African Republic", "value": "CF", "id": 43 },
    { "name": "Chad", "value": "TD", "id": 44 },
    { "name": "Chile", "value": "CL", "id": 45 },
    { "name": "China", "value": "CN", "id": 46 },
    { "name": "Christmas Island", "value": "CX", "id": 47 },
    { "name": "Cocos (Keeling) Islands", "value": "CC", "id": 48 },
    { "name": "Colombia", "value": "CO", "id": 49 },
    { "name": "Comoros", "value": "KM", "id": 50 },
    { "name": "Congo", "value": "CG", "id": 51 },
    { "name": "Congo, Democratic Republic of the Congo", "value": "CD", "id": 52 },
    { "name": "Cook Islands", "value": "CK", "id": 53 },
    { "name": "Costa Rica", "value": "CR", "id": 54 },
    { "name": "Cote D'Ivoire", "value": "CI", "id": 55 },
    { "name": "Croatia", "value": "HR", "id": 56 },
    { "name": "Cuba", "value": "CU", "id": 57 },
    { "name": "Curacao", "value": "CW", "id": 58 },
    { "name": "Cyprus", "value": "CY", "id": 59 },
    { "name": "Czech Republic", "value": "CZ", "id": 60 },
    { "name": "Denmark", "value": "DK", "id": 61 },
    { "name": "Djibouti", "value": "DJ", "id": 62 },
    { "name": "Dominica", "value": "DM", "id": 63 },
    { "name": "Dominican Republic", "value": "DO", "id": 64 },
    { "name": "Ecuador", "value": "EC", "id": 65 },
    { "name": "Egypt", "value": "EG", "id": 66 },
    { "name": "El Salvador", "value": "SV", "id": 67 },
    { "name": "Equatorial Guinea", "value": "GQ", "id": 68 },
    { "name": "Eritrea", "value": "ER", "id": 69 },
    { "name": "Estonia", "value": "EE", "id": 70 },
    { "name": "Ethiopia", "value": "ET", "id": 71 },
    { "name": "Falkland Islands (Malvinas)", "value": "FK", "id": 72 },
    { "name": "Faroe Islands", "value": "FO", "id": 73 },
    { "name": "Fiji", "value": "FJ", "id": 74 },
    { "name": "Finland", "value": "FI", "id": 75 },
    { "name": "France", "value": "FR", "id": 76 },
    { "name": "French Guiana", "value": "GF", "id": 77 },
    { "name": "French Polynesia", "value": "PF", "id": 78 },
    { "name": "French Southern Territories", "value": "TF", "id": 79 },
    { "name": "Gabon", "value": "GA", "id": 80 },
    { "name": "Gambia", "value": "GM", "id": 81 },
    { "name": "Georgia", "value": "GE", "id": 82 },
    { "name": "Germany", "value": "DE", "id": 83 },
    { "name": "Ghana", "value": "GH", "id": 84 },
    { "name": "Gibraltar", "value": "GI", "id": 85 },
    { "name": "Greece", "value": "GR", "id": 86 },
    { "name": "Greenland", "value": "GL", "id": 87 },
    { "name": "Grenada", "value": "GD", "id": 88 },
    { "name": "Guadeloupe", "value": "GP", "id": 89 },
    { "name": "Guam", "value": "GU", "id": 90 },
    { "name": "Guatemala", "value": "GT", "id": 91 },
    { "name": "Guernsey", "value": "GG", "id": 92 },
    { "name": "Guinea", "value": "GN", "id": 93 },
    { "name": "Guinea-Bissau", "value": "GW", "id": 94 },
    { "name": "Guyana", "value": "GY", "id": 95 },
    { "name": "Haiti", "value": "HT", "id": 96 },
    { "name": "Heard Island and McDonald Islands", "value": "HM", "id": 97 },
    { "name": "Holy See (Vatican City State)", "value": "VA", "id": 98 },
    { "name": "Honduras", "value": "HN", "id": 99 },
    { "name": "Hong Kong", "value": "HK", "id": 100 },
    { "name": "Hungary", "value": "HU", "id": 101 },
    { "name": "Iceland", "value": "IS", "id": 102 },
    { "name": "India", "value": "IN", "id": 103 },
    { "name": "Indonesia", "value": "ID", "id": 104 },
    { "name": "Iran, Islamic Republic of", "value": "IR", "id": 105 },
    { "name": "Iraq", "value": "IQ", "id": 106 },
    { "name": "Ireland", "value": "IE", "id": 107 },
    { "name": "Isle of Man", "value": "IM", "id": 108 },
    { "name": "Israel", "value": "IL", "id": 109 },
    { "name": "Italy", "value": "IT", "id": 110 },
    { "name": "Jamaica", "value": "JM", "id": 111 },
    { "name": "Japan", "value": "JP", "id": 112 },
    { "name": "Jersey", "value": "JE", "id": 113 },
    { "name": "Jordan", "value": "JO", "id": 114 },
    { "name": "Kazakhstan", "value": "KZ", "id": 115 },
    { "name": "Kenya", "value": "KE", "id": 116 },
    { "name": "Kiribati", "value": "KI", "id": 117 },
    { "name": "Korea, Democratic People's Republic of", "value": "KP", "id": 118 },
    { "name": "Korea, Republic of", "value": "KR", "id": 119 },
    { "name": "Kosovo", "value": "XK", "id": 120 },
    { "name": "Kuwait", "value": "KW", "id": 121 },
    { "name": "Kyrgyzstan", "value": "KG", "id": 122 },
    { "name": "Lao People's Democratic Republic", "value": "LA", "id": 123 },
    { "name": "Latvia", "value": "LV", "id": 124 },
    { "name": "Lebanon", "value": "LB", "id": 125 },
    { "name": "Lesotho", "value": "LS", "id": 126 },
    { "name": "Liberia", "value": "LR", "id": 127 },
    { "name": "Libyan Arab Jamahiriya", "value": "LY", "id": 128 },
    { "name": "Liechtenstein", "value": "LI", "id": 129 },
    { "name": "Lithuania", "value": "LT", "id": 130 },
    { "name": "Luxembourg", "value": "LU", "id": 131 },
    { "name": "Macao", "value": "MO", "id": 132 },
    { "name": "Macedonia, the Former Yugoslav Republic of", "value": "MK", "id": 133 },
    { "name": "Madagascar", "value": "MG", "id": 134 },
    { "name": "Malawi", "value": "MW", "id": 135 },
    { "name": "Malaysia", "value": "MY", "id": 136 },
    { "name": "Maldives", "value": "MV", "id": 137 },
    { "name": "Mali", "value": "ML", "id": 138 },
    { "name": "Malta", "value": "MT", "id": 139 },
    { "name": "Marshall Islands", "value": "MH", "id": 140 },
    { "name": "Martinique", "value": "MQ", "id": 141 },
    { "name": "Mauritania", "value": "MR", "id": 142 },
    { "name": "Mauritius", "value": "MU", "id": 143 },
    { "name": "Mayotte", "value": "YT", "id": 144 },
    { "name": "Mexico", "value": "MX", "id": 145 },
    { "name": "Micronesia, Federated States of", "value": "FM", "id": 146 },
    { "name": "Moldova, Republic of", "value": "MD", "id": 147 },
    { "name": "Monaco", "value": "MC", "id": 148 },
    { "name": "Mongolia", "value": "MN", "id": 149 },
    { "name": "Montenegro", "value": "ME", "id": 150 },
    { "name": "Montserrat", "value": "MS", "id": 151 },
    { "name": "Morocco", "value": "MA", "id": 152 },
    { "name": "Mozambique", "value": "MZ", "id": 153 },
    { "name": "Myanmar", "value": "MM", "id": 154 },
    { "name": "Namibia", "value": "NA", "id": 155 },
    { "name": "Nauru", "value": "NR", "id": 156 },
    { "name": "Nepal", "value": "NP", "id": 157 },
    { "name": "Netherlands", "value": "NL", "id": 158 },
    { "name": "Netherlands Antilles", "value": "AN", "id": 159 },
    { "name": "New Caledonia", "value": "NC", "id": 160 },
    { "name": "New Zealand", "value": "NZ", "id": 161 },
    { "name": "Nicaragua", "value": "NI", "id": 162 },
    { "name": "Niger", "value": "NE", "id": 163 },
    { "name": "Nigeria", "value": "NG", "id": 164 },
    { "name": "Niue", "value": "NU", "id": 165 },
    { "name": "Norfolk Island", "value": "NF", "id": 166 },
    { "name": "Northern Mariana Islands", "value": "MP", "id": 167 },
    { "name": "Norway", "value": "NO", "id": 168 },
    { "name": "Oman", "value": "OM", "id": 169 },
    { "name": "Pakistan", "value": "PK", "id": 170 },
    { "name": "Palau", "value": "PW", "id": 171 },
    { "name": "Palestinian Territory, Occupied", "value": "PS", "id": 172 },
    { "name": "Panama", "value": "PA", "id": 173 },
    { "name": "Papua New Guinea", "value": "PG", "id": 174 },
    { "name": "Paraguay", "value": "PY", "id": 175 },
    { "name": "Peru", "value": "PE", "id": 176 },
    { "name": "Philippines", "value": "PH", "id": 177 },
    { "name": "Pitcairn", "value": "PN", "id": 178 },
    { "name": "Poland", "value": "PL", "id": 179 },
    { "name": "Portugal", "value": "PT", "id": 180 },
    { "name": "Puerto Rico", "value": "PR", "id": 181 },
    { "name": "Qatar", "value": "QA", "id": 182 },
    { "name": "Reunion", "value": "RE", "id": 183 },
    { "name": "Romania", "value": "RO", "id": 184 },
    { "name": "Russian Federation", "value": "RU", "id": 185 },
    { "name": "Rwanda", "value": "RW", "id": 186 },
    { "name": "Saint Barthelemy", "value": "BL", "id": 187 },
    { "name": "Saint Helena", "value": "SH", "id": 188 },
    { "name": "Saint Kitts and Nevis", "value": "KN", "id": 189 },
    { "name": "Saint Lucia", "value": "LC", "id": 190 },
    { "name": "Saint Martin", "value": "MF", "id": 191 },
    { "name": "Saint Pierre and Miquelon", "value": "PM", "id": 192 },
    { "name": "Saint Vincent and the Grenadines", "value": "VC", "id": 193 },
    { "name": "Samoa", "value": "WS", "id": 194 },
    { "name": "San Marino", "value": "SM", "id": 195 },
    { "name": "Sao Tome and Principe", "value": "ST", "id": 196 },
    { "name": "Saudi Arabia", "value": "SA", "id": 197 },
    { "name": "Senegal", "value": "SN", "id": 198 },
    { "name": "Serbia", "value": "RS", "id": 199 },
    { "name": "Serbia and Montenegro", "value": "CS", "id": 200 },
    { "name": "Seychelles", "value": "SC", "id": 201 },
    { "name": "Sierra Leone", "value": "SL", "id": 202 },
    { "name": "Singapore", "value": "SG", "id": 203 },
    { "name": "St Martin", "value": "SX", "id": 204 },
    { "name": "Slovakia", "value": "SK", "id": 205 },
    { "name": "Slovenia", "value": "SI", "id": 206 },
    { "name": "Solomon Islands", "value": "SB", "id": 207 },
    { "name": "Somalia", "value": "SO", "id": 208 },
    { "name": "South Africa", "value": "ZA", "id": 209 },
    { "name": "South Georgia and the South Sandwich Islands", "value": "GS", "id": 210 },
    { "name": "South Sudan", "value": "SS", "id": 211 },
    { "name": "Spain", "value": "ES", "id": 212 },
    { "name": "Sri Lanka", "value": "LK", "id": 213 },
    { "name": "Sudan", "value": "SD", "id": 214 },
    { "name": "Suri", "value": "SR", "id": 215 },
    { "name": "Svalbard and Jan Mayen", "value": "SJ", "id": 216 },
    { "name": "Swaziland", "value": "SZ", "id": 217 },
    { "name": "Sweden", "value": "SE", "id": 218 },
    { "name": "Switzerland", "value": "CH", "id": 219 },
    { "name": "Syrian Arab Republic", "value": "SY", "id": 220 },
    { "name": "Taiwan, Province of China", "value": "TW", "id": 221 },
    { "name": "Tajikistan", "value": "TJ", "id": 222 },
    { "name": "Tanzania, United Republic of", "value": "TZ", "id": 223 },
    { "name": "Thailand", "value": "TH", "id": 224 },
    { "name": "Timor-Leste", "value": "TL", "id": 225 },
    { "name": "Togo", "value": "TG", "id": 226 },
    { "name": "Tokelau", "value": "TK", "id": 227 },
    { "name": "Tonga", "value": "TO", "id": 228 },
    { "name": "Trinidad and Tobago", "value": "TT", "id": 229 },
    { "name": "Tunisia", "value": "TN", "id": 230 },
    { "name": "Turkey", "value": "TR", "id": 231 },
    { "name": "Turkmenistan", "value": "TM", "id": 232 },
    { "name": "Turks and Caicos Islands", "value": "TC", "id": 233 },
    { "name": "Tuvalu", "value": "TV", "id": 234 },
    { "name": "Uganda", "value": "UG", "id": 235 },
    { "name": "Ukraine", "value": "UA", "id": 236 },
    { "name": "United Arab Emirates", "value": "AE", "id": 237 },
    { "name": "United Kingdom", "value": "GB", "id": 238 },
    { "name": "United States", "value": "US", "id": 239 },
    { "name": "United States Minor Outlying Islands", "value": "UM", "id": 240 },
    { "name": "Uruguay", "value": "UY", "id": 241 },
    { "name": "Uzbekistan", "value": "UZ", "id": 242 },
    { "name": "Vanuatu", "value": "VU", "id": 243 },
    { "name": "Venezuela", "value": "VE", "id": 244 },
    { "name": "Viet Nam", "value": "VN", "id": 245 },
    { "name": "Virgin Islands, British", "value": "VG", "id": 246 },
    { "name": "Virgin Islands, U.s.", "value": "VI", "id": 247 },
    { "name": "Wallis and Futuna", "value": "WF", "id": 248 },
    { "name": "Western Sahara", "value": "EH", "id": 249 },
    { "name": "Yemen", "value": "YE", "id": 250 },
    { "name": "Zambia", "value": "ZM", "id": 251 },
    { "name": "Zimbabwe", "value": "ZW", "id": 252 }
];